/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/downloads': RouteRecordInfo<
      '/downloads',
      '/downloads',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feeds': RouteRecordInfo<
      '/feeds',
      '/feeds',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/following': RouteRecordInfo<
      '/following',
      '/following',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/history': RouteRecordInfo<
      '/history',
      '/history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/library': RouteRecordInfo<
      '/library',
      '/library',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/likes': RouteRecordInfo<
      '/likes',
      '/likes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/radio': RouteRecordInfo<
      '/radio',
      '/radio',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/search/[query]': RouteRecordInfo<
      '/search/[query]',
      '/search/:query',
      { query: ParamValue<true> },
      { query: ParamValue<false> },
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system-playlist/[urn]': RouteRecordInfo<
      '/system-playlist/[urn]',
      '/system-playlist/:urn',
      { urn: ParamValue<true> },
      { urn: ParamValue<false> },
      | never
    >,
    '/tag/[tag]': RouteRecordInfo<
      '/tag/[tag]',
      '/tag/:tag',
      { tag: ParamValue<true> },
      { tag: ParamValue<false> },
      | never
    >,
    '/test': RouteRecordInfo<
      '/test',
      '/test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/track/[id]': RouteRecordInfo<
      '/track/[id]',
      '/track/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/user/[id]': RouteRecordInfo<
      '/user/[id]',
      '/user/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/user-playlist/[id]': RouteRecordInfo<
      '/user-playlist/[id]',
      '/user-playlist/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/downloads.vue': {
      routes:
        | '/downloads'
      views:
        | never
    }
    'src/pages/feeds.vue': {
      routes:
        | '/feeds'
      views:
        | never
    }
    'src/pages/following.vue': {
      routes:
        | '/following'
      views:
        | never
    }
    'src/pages/history.vue': {
      routes:
        | '/history'
      views:
        | never
    }
    'src/pages/library.vue': {
      routes:
        | '/library'
      views:
        | never
    }
    'src/pages/likes.vue': {
      routes:
        | '/likes'
      views:
        | never
    }
    'src/pages/radio.vue': {
      routes:
        | '/radio'
      views:
        | never
    }
    'src/pages/search/[query].vue': {
      routes:
        | '/search/[query]'
      views:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
      views:
        | never
    }
    'src/pages/system-playlist/[urn].vue': {
      routes:
        | '/system-playlist/[urn]'
      views:
        | never
    }
    'src/pages/tag/[tag].vue': {
      routes:
        | '/tag/[tag]'
      views:
        | never
    }
    'src/pages/test.vue': {
      routes:
        | '/test'
      views:
        | never
    }
    'src/pages/track/[id].vue': {
      routes:
        | '/track/[id]'
      views:
        | never
    }
    'src/pages/user/[id].vue': {
      routes:
        | '/user/[id]'
      views:
        | never
    }
    'src/pages/user-playlist/[id].vue': {
      routes:
        | '/user-playlist/[id]'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
