// Private soundcloud types, Generated by quicktype
// https://app.quicktype.io

export interface TrackLike {
  created_at: Date
  kind: TrackLikeKind
  track: Track
}

export type TrackLikeKind = "like"

export interface PartialTrack {
  id: number
  kind: TrackKind
  monetization_model: MonetizationModel
  policy: Policy
}

export interface Track extends PartialTrack {
  artwork_url: null | string
  caption: null | string
  commentable: boolean
  comment_count: number | null
  created_at: Date
  description: null | string
  downloadable: boolean
  download_count: number | null
  duration: number // will be affected by SNIP
  full_duration: number // will not be affected by POLICY
  embeddable_by: EmbeddableBy
  genre: null | string
  has_downloads_left: boolean
  label_name: null | string
  last_modified: Date
  license: License
  likes_count: number | null
  permalink: string
  permalink_url: string
  playback_count: number | null
  public: boolean
  publisher_metadata: PublisherMetadata | null
  purchase_title: null | string
  purchase_url: null | string
  release_date: Date | null
  reposts_count: number
  secret_token: null
  sharing: Sharing
  state: State
  streamable: boolean
  tag_list: string
  title: string
  uri: string
  urn: string
  user_id: number
  visuals: Visuals | null
  waveform_url: string
  display_date: Date
  media: Media
  station_urn: string
  station_permalink: string
  track_authorization: string
  user: User
}

export type EmbeddableBy = "all" | "me"

export type TrackKind = "track"

export type License = "all-rights-reserved" | "cc-by-nc-sa" | "cc-by" | "cc-by-nc"

export interface Media {
  transcodings: Transcoding[]
}

export interface Transcoding {
  url: string
  preset: Preset
  duration: number // in millis
  snipped: boolean
  format: Format
  quality: Quality
  is_legacy_transcoding: boolean
}

export interface Format {
  protocol: Protocol
  mime_type: MIMEType
}

export type MIMEType =
  | 'audio/mp4; codecs="mp4a.40.2"'
  | "audio/mpegurl"
  | "audio/mpeg"
  | 'audio/ogg; codecs="opus"'

export type Protocol = "hls" | "progressive" | "ctr-encrypted-hls" | "cbc-encrypted-hls" // TODO: Encrypted HLS currently not supported

export const PRESET_ORDER = [
  // Non-legacy transcodings
  "aac_256k",
  "aac_160k",
  "abr_sq",
  // "abr_hq", is there an option?
  // Legacy transcodings (being removed soom: https://developers.soundcloud.com/blog/api-streaming-urls)
  "mp3_1_0",
  "opus_0_0",
  "mp3_0_1",
  "mp3_standard",
  "mp3_0_0",
] as const

export type Preset = (typeof PRESET_ORDER)[number]

export type Quality = "sq" | "hq" // sq and hq makes no difference, only affects aac it seems

export type MonetizationModel = "NOT_APPLICABLE" | "AD_SUPPORTED" | "BLACKBOX"

export type Policy = "ALLOW" | "SNIP" | "BLOCK" | "MONETIZE" // Monetize is unknown

export interface PublisherMetadata {
  id: number
  urn: string
  artist?: string
  contains_music?: boolean
  publisher?: string
  isrc?: string
  explicit?: boolean
  writer_composer?: string
  album_title?: string
  p_line?: string
  p_line_for_display?: string
  release_title?: string
  iswc?: string
  upc_or_ean?: string
  c_line?: string
  c_line_for_display?: string
}

export type Sharing = "public"

export type State = "finished"

export interface SCUser {
  avatar_url: string
  city: null | string
  comments_count: number
  country_code: null | string
  created_at: Date
  creator_subscriptions: CreatorSubscription[]
  creator_subscription: CreatorSubscription
  description: null | string
  followers_count: number
  followings_count: number
  first_name: string
  full_name: string
  groups_count: number
  id: number
  kind: UserKind
  last_modified: Date
  last_name: string
  likes_count: number
  playlist_likes_count: number
  permalink: string
  permalink_url: string
  playlist_count: number
  reposts_count: number | null
  track_count: number
  uri: string
  urn: string
  username: string
  verified: boolean
  visuals: Visuals
  badges: Badges
  station_urn: string
  station_permalink: string
  date_of_birth: null
}

export interface CreatorSubscription {
  product: Product
}

export interface Product {
  id: ID
}

export type ID = "creator-pro-unlimited" | "free"

export interface User {
  avatar_url: string
  first_name: string
  followers_count: number
  full_name: string
  id: number
  kind: UserKind
  last_modified: Date
  last_name: string
  permalink: string
  permalink_url: string
  uri: string
  urn: string
  username: string
  verified: boolean
  city: null | string
  country_code: null | string
  badges: Badges
  station_urn: string
  station_permalink: string
}

export interface Badges {
  pro: boolean
  creator_mid_tier: boolean
  pro_unlimited: boolean
  verified: boolean
}

export type UserKind = "user" | "track"

export interface Visuals {
  urn: string
  enabled: boolean
  visuals: Visual[]
  tracking: null
}

export interface Visual {
  urn: string
  entry_time: number
  visual_url: string
}

interface PlaylistLikeBase {
  created_at: Date
  type: PlaylistLikeType
  user: User
  uuid: string
  caption: null
  playlist?: Playlist
  system_playlist?: SystemPlaylist
}

export type PlaylistLike = PlaylistLikeBase &
  (
    | { playlist: Playlist; system_playlist?: never }
    | { system_playlist: SystemPlaylist; playlist?: never }
  )

export interface BasePlaylist {
  id: number | string
  title: string
  tracks?: PartialTrack[]
}

export interface ExactPlaylist extends BasePlaylist {
  tracks: Track[]
}

export class LocalPlaylist {
  id: string
  title: string
  tracks: Track[] = []

  constructor(name: string) {
    this.id = name
    this.title = name
  }
}

export interface Playlist extends BasePlaylist {
  artwork_url: null | string
  created_at: Date
  duration: number
  id: number
  kind: PlaylistKind
  last_modified: Date
  likes_count: number
  managed_by_feeds: boolean
  permalink: string
  permalink_url: string
  public: boolean
  reposts_count: number
  secret_token: null
  sharing: Sharing
  title: string
  track_count: number
  uri: string
  user_id: number
  set_type: string
  is_album: boolean
  published_at: Date | null
  release_date: Date | null
  display_date: Date
  user: User
  tracks?: PartialTrack[]
}

export type PlaylistKind = "playlist"

export interface SystemPlaylist extends BasePlaylist {
  urn: string
  query_urn: null | string
  permalink: string
  permalink_url: string
  title: string
  description: string
  short_title: string
  short_description: null | string
  tracking_feature_name: string
  playlist_type: PlaylistType
  last_updated: Date | null
  artwork_url: string
  calculated_artwork_url: string
  likes_count: number
  seed: Seed | null
  tracks: PartialTrack[]
  is_public: boolean
  made_for: User | null
  user: User
  kind: SystemPlaylistKind
  id: string
}

export type SystemPlaylistKind = "system-playlist"

export type PlaylistType = "PLAYLIST" | "TRACK_STATION"

export interface Seed {
  urn: string
  permalink: string
}

export type PlaylistLikeType = "playlist-like" | "system-playlist-like"

export interface CollectionResp<T> {
  collection: T[]
  next_href: string | null
  query_urn: string | null
}

export const SOCIAL_NETWORKS = {
  bandpage: "BandPage",
  bandcamp: "Bandcamp",
  bandsintown: "Bandsintown",
  beatport: "Beatport",
  berklee: "Berklee",
  ccmixter: "ccMixter",
  discogs: "Discogs",
  facebook: "Facebook",
  flavors: "flavors.me",
  flickr: "Flickr",
  foursquare: "Foursquare",
  freesound: "Freesound",
  gigatools: "Gigatools",
  google_plus: "Google+",
  hypem: "Hype Machine",
  instagram: "Instagram",
  itunes_podcast: "iTunes Podcast",
  lastfm: "Last.fm",
  linktree: "Linktree",
  mixcloud: "Mixcloud",
  myspace: "MySpace",
  ning: "Ning",
  pinterest: "Pinterest",
  purevolume: "PureVolume",
  residentadvisor: "Resident Advisor",
  residentadvisorlabel: "Resident Advisor",
  reverbnation: "ReverbNation",
  snapchat: "Snapchat",
  songkick: "Songkick",
  soundcloud: "SoundCloud",
  spotify: "Spotify",
  thedjlist: "The DJ List",
  tumblr: "Tumblr",
  twitter: "Twitter",
  vimeo: "Vimeo",
  virb: "Virb",
  vkontakte: "VK",
  whatpeopleplay: "Whatpeopleplay",
  wordpress: "Wordpress",
  youtube: "YouTube",
  zeroinch: "zero",
}

export interface WebProfile {
  url: string
  network: string
  title: string
  username?: string
}

export interface Comment {
  kind: CommentKind
  id: number
  body: string
  created_at: Date
  timestamp: number
  track_id: number
  user_id: number
  self: Self
  user: User
  track: Track
}

export type CommentKind = "comment"

export interface Self {
  urn: string
}
